version: '2'

services:
  gyg.middleware:
        container_name: "middleware"
        mem_limit: 1G
        build: ./middleware
        ports:
            - "${MIDDLEWARE_PORT}:${MIDDLEWARE_PORT}"
        environment:
            SERVICE_NAME: middleware
            SERVICE_TAGS: local
            CONFIG_FILE_PATH: ${CONFIG_FILE_PATH}
        restart: always
